name: Update Leaderboard & Build Site

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib numpy

      - name: Update leaderboard
        run: python fetch_leaderboard.py

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: "."
          destination: "./_site"
