name: Update Leaderboard & Build Site

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # custom token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib numpy

      - name: Update leaderboard
        run: python -u fetch_leaderboard.py

      - name: Commit leaderboard.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add leaderboard.json
          git commit -m "Update leaderboard.json ($(date -u +"%Y-%m-%d %H:%M:%S UTC"))" || echo "No changes to commit"
          git push

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: "."
          destination: "./_site"
